### ISSUE TITLE
How are API keys sent in API requests?

### ISSUE THREAD

**Issue by Scripter17** [bypass-vip/bypass.vip#8]
I've implemented bypass.vip support in my project [URL Cleaner](https://github.com/Scripter17/url-cleaner) and I want to provide an option for people to provide their API key.

I don't need a key since I don't run into linkvertise more than once a second but I'd like to at least support it for those who do. I assume it's just a `&token=abcdef`-type thing at the end of the URL?

Great work by the way! I'm really glad I didn't have to do linkvertise myself.

Side note: While URL Cleaner does finally do its own caching and using bypass.vip is opt-in, if there's concerns about excessive load from people using the [Tampermonkey script + HTTP Server](https://github.com/Scripter17/url-cleaner-site) I'm fully willing to remove it.

**Comment by throat** [comment]
Hi, the API key is sent in the request header 'x-api-key', API keys are a UUID4 (In case you want some extra checking)
There are currently 2 premium API endpoints:
/premium/bypass (Private proxies and private Linkvertise premium accounts will be used for new links)
/premium/refresh (Skips cache/DB lookup and does a new bypass)

These endpoints also return extra metadata about the requested content under the keys link_metadata and user_metadata.

Thank you for the kind words! I checked out your project, and I'm very impressed! Please let me know when you got a binary with the full integration, so I can check it out. (Rust looks like dark magic to me)
Since it's open source I'd like to give you a free premium API key, please send me a PM on Discord @ bypass.vip :)

Also, no worries about server stress. We have a pretty strong cache and a built-in rate limiter & if users are premium, there's no request limit anyway.

**Comment by Scripter17** [comment]
I released v0.3.2 just now

Assuming you're on x86 Linux (and have the right libraries installed, which for me required installing `libssl-dev` and `libsqlite3-dev`), the following binary should work for you: 
[url-cleaner.zip](https://github.com/user-attachments/files/16380743/url-cleaner.zip)

You can invoke it with `./url-cleaner -f bypass.vip -v bypass.vip-api-key=$URL_CLEANER_BYPASS_VIP_API_KEY "$some_linkvertise_url"` (you can just use the environment variable)

And yes I did make a mess of the releases. I'm new to actually doing stuff seriously.

**Comment by Scripter17** [comment]
Also closing as the "issue" is technically resolved
